name: test

#REDIS CONFIGURATION
spring:
  redis:
    database: 0
    timeout: 7200
    password: rss123
    lettuce:
        pool:
          max-active: 32
          max-idle: 32
          min-idle: 16
          max-wait: -1
    sentinel:
      master: mymaster
      nodes : 10.80.248.24:26379